//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int ArabaId { get; set; }
        public string ArabaMarkası { get; set; }
        public string ArabaModeli { get; set; }
        public string ArabaVites { get; set; }
        public string ArabaYılı { get; set; }
        public string ArabaYakıt { get; set; }
        public string ArabaKasa { get; set; }
        public Nullable<int> ArabaUcret { get; set; }
    }
}
